version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
  vendor-store:
  node_modules-store:
services:
  app:
    build: ./infra/docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
      - vendor-store:/work/backend/vendor

  web:
    build: ./infra/docker/nginx
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
      - node_modules-store:/work/backend/node_modules

  db:
    build: ./infra/docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
