name: laravel-git-clone

on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Laravel Project Git Clone
        run: git clone https://github.com/laravel/laravel.git backend
      - name: Docker Compose Version
        run: docker-compose --version
      - name: Build Docker
        run: |
          cd infrastructure
          docker-compose build
          docker-compose up -d
      - name: Composer Install
        run: |
          cd infrastructure
          docker-compose exec -T app php --version
          docker-compose exec -T app composer --version
          docker-compose exec -T app composer install
      - name: Laravel Settings
        run: |
          cd infrastructure
          docker-compose exec -T app cp .env.example .env
          docker-compose exec -T app php artisan key:generate
          docker-compose exec -T app php artisan storage:link
      - name: PHP and Laravel Version
        run: |
          cd infrastructure
          docker-compose exec -T app php artisan --version
      - name: Laravel Migrate, Rollback, Seeding Testing
        run: |
          cd infrastructure
          docker-compose exec -T app php artisan migrate
          docker-compose exec -T app php artisan migrate:refresh --seed
      - name: Laravel Testing
        run: |
          cd infrastructure
          docker-compose exec -T app php artisan test
