name: Laravel Git Clone
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  laravel-git-clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Git Clone Project
        run: git clone https://github.com/laravel/laravel.git src
      - name: Docker Version
        run: docker version
      - name: Docker Compose Settings
        run: |
          echo APP_BUILD_TARGET=development-xdebug > .env
          echo "UID=$(id -u)" >> .env
          echo "GID=$(id -g)" >> .env
      - name: Build Docker Images
        run: docker compose build
      - name: Create & Start Docker Containers
        run: docker compose up -d
      - name: OS Version
        run: |
          docker compose exec app cat /etc/os-release
          docker compose exec app cat /etc/debian_version
      - name: PHP Version
        run: docker compose exec app php --version
      - name: Composer Version
        run: docker compose exec app composer --version
      - name: Composer Install
        run: docker compose exec app composer install
      - name: Laravel Version
        run: docker compose exec app php artisan --version
      - name: Laravel Settings
        run: |
          docker compose exec app cp .env.example .env
          docker compose exec app php artisan key:generate
      - name: Wait for the MySQL container to start
        run: sleep 5s
        shell: bash
      - name: Laravel Migrate Testing
        run: docker compose exec app php artisan migrate
      - name: Laravel Rollback Testing
        run: docker compose exec app php artisan migrate:refresh
      - name: Laravel Seeding Testing
        run: docker compose exec app php artisan db:seed
      - name: Laravel PHPUnit Testing
        run: docker compose exec app php artisan test
